server:
  port: 8080
  servlet:
    context-path: /client2
 
client2.message: "I am client2"
demo.message: "InvokeRefresh working as expected - Test from push local"
management.endpoints.web.exposure.include: "*"
