server:
  port: 8080
  servlet:
    context-path: /client2
 
client2.message: "I am client2"
demo.message: "Test Busrefresh yet again Attempt 7 - Monitor"
management.endpoints.web.exposure.include: "*"
